import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage, type RGB } from "pdf-lib";
import { pdfSafe, pdfSafeName } from "./pdf-text";

// Workers-safe port of the rate-card PDF that used to be generated by pdfkit on
// the standalone nochill-rate-card Vercel app. pdfkit cannot run here — it reads
// its Helvetica .afm metrics off disk via `fs`, which does not exist on
// Cloudflare Workers. pdf-lib is pure JS with the 14 standard fonts built in, and
// was already a declared dependency, so the whole tool can live on chkplt.com.
//
// Two coordinate differences from the pdfkit original, handled by the helpers:
//   1. pdf-lib's origin is BOTTOM-left; pdfkit's is TOP-left. Every y below is
//      still written top-down (matching the original source line for line) and
//      converted once, in drawText/rect.
//   2. pdf-lib positions text by BASELINE, pdfkit by the top of the line box.
//      BASELINE_RATIO converts. It also has no characterSpacing, so tracked
//      caps labels are drawn glyph by glyph.
//
// Deliberately dropped: 6px corner radii (pdf-lib has no roundedRect; at 6px on
// an A4-ish page the difference is invisible). Everything else — the palette,
// the band heights, the type sizes — is the original layout.

const GOLD = rgb(0xc9 / 255, 0xa8 / 255, 0x4c / 255);
const DARK = rgb(0x1c / 255, 0x1c / 255, 0x1c / 255);
const WHITE = rgb(1, 1, 1);
const PAPER = rgb(0xf8 / 255, 0xf8 / 255, 0xf8 / 255);
const GRAY = rgb(0x88 / 255, 0x88 / 255, 0x88 / 255);
const BORDER = rgb(0xe0 / 255, 0xe0 / 255, 0xe0 / 255);
const GOLD_TINT = rgb(0xfd / 255, 0xf8 / 255, 0xee / 255);
const GOLD_BDR = rgb(0xd4 / 255, 0xb2 / 255, 0x6a / 255);
const DIVIDER = rgb(0x33 / 255, 0x33 / 255, 0x33 / 255);
const HAIRLINE = rgb(0xf0 / 255, 0xf0 / 255, 0xf0 / 255);

const W = 794;
const H = 1123;
const PAD = 56;
const COL = W - PAD * 2; // 682
const BASELINE_RATIO = 0.8;

export interface RateCardData {
  creatorName?: string;
  handle?: string;
  platform?: string;
  tier?: string;
  er?: string;
  erLabel?: string;
  floor?: string;
  standard?: string;
  ceiling?: string;
  followers?: string;
  date?: string;
  brand?: string;
}

type Align = "left" | "center" | "right";

interface TextOpts {
  x: number;
  top: number;
  size: number;
  font: PDFFont;
  color: RGB;
  opacity?: number;
  tracking?: number;
  align?: Align;
  width?: number;
}

function measure(font: PDFFont, text: string, size: number, tracking = 0): number {
  return font.widthOfTextAtSize(text, size) + tracking * Math.max(0, text.length - 1);
}

function drawText(page: PDFPage, raw: string, o: TextOpts): void {
  // Sanitised here so no caller can bypass it — a non-Latin creator name would
  // otherwise throw inside pdf-lib and 500 the whole delivery request.
  const text = pdfSafe(raw);
  const { x, top, size, font, color, opacity = 1, tracking = 0, align = "left", width } = o;
  const y = H - (top + size * BASELINE_RATIO);
  let startX = x;
  if (align !== "left" && width != null) {
    const w = measure(font, text, size, tracking);
    startX = align === "center" ? x + (width - w) / 2 : x + width - w;
  }
  if (!tracking) {
    page.drawText(text, { x: startX, y, size, font, color, opacity });
    return;
  }
  let cursor = startX;
  for (const ch of text) {
    page.drawText(ch, { x: cursor, y, size, font, color, opacity });
    cursor += font.widthOfTextAtSize(ch, size) + tracking;
  }
}

function rect(
  page: PDFPage,
  x: number,
  top: number,
  w: number,
  h: number,
  fill?: RGB,
  opts?: { border?: RGB; opacity?: number },
): void {
  page.drawRectangle({
    x,
    y: H - top - h,
    width: w,
    height: h,
    ...(fill ? { color: fill } : {}),
    ...(opts?.border ? { borderColor: opts.border, borderWidth: 1 } : {}),
    ...(opts?.opacity != null ? { opacity: opts.opacity, borderOpacity: opts.opacity } : {}),
  });
}

// pdfkit wrapped the engagement paragraph itself; pdf-lib does not wrap at all.
function wrap(font: PDFFont, raw: string, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  let line = "";
  for (const word of pdfSafe(raw).split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function generateRateCardPDF(d: RateCardData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("Creator Rate Card — NOCHILL");
  const page = doc.addPage([W, H]);
  const reg = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  // "Instagram · Parenting & Family · Reel / Short Video"
  const parts = (d.platform || "").split(" · ");
  const platformName = parts[0] || "";
  const niche = parts[1] || "";
  const contentType = parts[2] || "";
  const handle = (d.handle || "").trim();
  const er = parseFloat(d.er ?? "") || 0;
  const xSA = (er / 3.39).toFixed(1);
  const xGlobal = (er / 1.49).toFixed(1);

  // 1. Page background
  rect(page, 0, 0, W, H, PAPER);

  // 2. Header band
  rect(page, 0, 0, W, 92, DARK);
  drawText(page, "CREATOR RATE CARD  ·  NOCHILL", {
    x: PAD,
    top: 22,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 2.2,
  });
  drawText(page, pdfSafeName(d.creatorName).toUpperCase(), {
    x: PAD,
    top: 36,
    size: 26,
    font: bold,
    color: WHITE,
  });
  drawText(page, d.tier || "", {
    x: 0,
    top: 26,
    size: 10,
    font: bold,
    color: GOLD,
    align: "right",
    width: W - PAD,
  });
  drawText(page, `${platformName}${niche ? " · " + niche : ""}`, {
    x: 0,
    top: 42,
    size: 9,
    font: reg,
    color: WHITE,
    opacity: 0.6,
    align: "right",
    width: W - PAD,
  });

  // 3. Gold stripe
  rect(page, 0, 92, W, 4, GOLD);

  // 4. Stats strip
  rect(page, 0, 96, W, 84, DARK);
  const stats = [
    { label: "PLATFORM", value: platformName || "—" },
    { label: "FOLLOWERS", value: d.followers || "—" },
    { label: "ENGAGEMENT RATE", value: `${d.er || "0"}%` },
    { label: "CONTENT TYPE", value: contentType || "—" },
  ];
  const cellW = W / 4;
  stats.forEach((stat, i) => {
    const cx = i * cellW;
    if (i > 0) rect(page, cx, 108, 1, 56, DIVIDER);
    drawText(page, stat.label, {
      x: cx,
      top: 110,
      size: 7,
      font: bold,
      color: GRAY,
      tracking: 1.5,
      align: "center",
      width: cellW,
    });
    drawText(page, stat.value, {
      x: cx,
      top: 127,
      size: 16,
      font: bold,
      color: GOLD,
      align: "center",
      width: cellW,
    });
  });
  if (d.erLabel) {
    drawText(page, d.erLabel, {
      x: cellW * 2,
      top: 148,
      size: 8,
      font: reg,
      color: WHITE,
      opacity: 0.4,
      align: "center",
      width: cellW,
    });
  }

  // 5. Bottom gold stripe
  rect(page, 0, 180, W, 4, GOLD);

  // 6. Rate section label
  const lblY = 208;
  rect(page, PAD, lblY - 10, COL, 1, GOLD, { opacity: 0.2 });
  drawText(page, "YOUR RATES — BACKED BY 2024/2025 AFRICAN CPM DATA", {
    x: PAD,
    top: lblY,
    size: 7.5,
    font: bold,
    color: GRAY,
    tracking: 1.5,
  });

  // 7. Three rate boxes
  const boxY = 230;
  const boxH = 120;
  const boxW = (COL - 20) / 3;

  rect(page, PAD, boxY, boxW, boxH, WHITE, { border: BORDER });
  drawText(page, "FLOOR RATE", {
    x: PAD,
    top: boxY + 14,
    size: 7.5,
    font: bold,
    color: GRAY,
    tracking: 1.5,
    align: "center",
    width: boxW,
  });
  drawText(page, d.floor || "R 0", {
    x: PAD,
    top: boxY + 38,
    size: 22,
    font: bold,
    color: DARK,
    align: "center",
    width: boxW,
  });
  drawText(page, "Minimum — non-negotiable", {
    x: PAD,
    top: boxY + 94,
    size: 9,
    font: reg,
    color: GRAY,
    align: "center",
    width: boxW,
  });

  const recX = PAD + boxW + 10;
  rect(page, recX, boxY, boxW, boxH, GOLD_TINT, { border: GOLD_BDR });
  rect(page, recX, boxY, boxW, 18, GOLD);
  drawText(page, "RECOMMENDED", {
    x: recX,
    top: boxY + 5,
    size: 7,
    font: bold,
    color: DARK,
    tracking: 1,
    align: "center",
    width: boxW,
  });
  drawText(page, "STANDARD RATE", {
    x: recX,
    top: boxY + 24,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
    align: "center",
    width: boxW,
  });
  drawText(page, d.standard || "R 0", {
    x: recX,
    top: boxY + 38,
    size: 36,
    font: bold,
    color: DARK,
    align: "center",
    width: boxW,
  });
  drawText(page, "Your opening quote to brands", {
    x: recX,
    top: boxY + 98,
    size: 9,
    font: reg,
    color: DARK,
    opacity: 0.5,
    align: "center",
    width: boxW,
  });

  const premX = recX + boxW + 10;
  rect(page, premX, boxY, boxW, boxH, WHITE, { border: BORDER });
  drawText(page, "PREMIUM RATE", {
    x: premX,
    top: boxY + 14,
    size: 7.5,
    font: bold,
    color: GRAY,
    tracking: 1.5,
    align: "center",
    width: boxW,
  });
  drawText(page, d.ceiling || "R 0", {
    x: premX,
    top: boxY + 38,
    size: 22,
    font: bold,
    color: DARK,
    align: "center",
    width: boxW,
  });
  drawText(page, "Full rights + exclusivity", {
    x: premX,
    top: boxY + 94,
    size: 9,
    font: reg,
    color: GRAY,
    align: "center",
    width: boxW,
  });

  // 8. Divider
  const div1Y = boxY + boxH + 20;
  rect(page, PAD, div1Y, COL, 1, BORDER);

  // 9. Creator profile / Contact & booking
  const detY = div1Y + 28;
  const half = COL / 2 - 10;
  const ROW = 34;

  drawText(page, "CREATOR PROFILE", {
    x: PAD,
    top: detY,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
  });
  const profileRows: [string, string][] = [
    ["Platform", platformName || "—"],
    ["Niche", niche || "—"],
    ["Content Type", contentType || "—"],
    ["Followers", d.followers || "—"],
    ["Engagement Rate", `${d.er || "0"}% (${d.erLabel || ""})`],
  ];
  profileRows.forEach(([label, value], i) => {
    const ry = detY + 20 + i * ROW;
    drawText(page, label, { x: PAD, top: ry, size: 10.5, font: reg, color: GRAY });
    drawText(page, value, {
      x: PAD,
      top: ry,
      size: 10.5,
      font: bold,
      color: DARK,
      align: "right",
      width: half,
    });
    if (i < profileRows.length - 1) rect(page, PAD, ry + 26, half, 0.5, HAIRLINE);
  });

  const col2X = PAD + half + 20;
  drawText(page, "CONTACT & BOOKING", {
    x: col2X,
    top: detY,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
  });
  const contactRows: [string, string][] = [
    ["Name", d.creatorName || "—"],
    ["Handle", handle ? handle : `DM via ${platformName || "social media"}`],
    ["Date", d.date || ""],
    ...(d.brand ? ([["Prepared for", d.brand]] as [string, string][]) : []),
    ["Status", "Available for brand collaborations"],
    ["Next step", "Reply to this email to start"],
  ];
  contactRows.forEach(([label, value], i) => {
    const ry = detY + 20 + i * ROW;
    drawText(page, label, { x: col2X, top: ry, size: 10.5, font: reg, color: GRAY });
    const accent = label === "Handle" || label === "Prepared for";
    drawText(page, value, {
      x: col2X,
      top: ry,
      size: 10.5,
      font: bold,
      color: accent ? GOLD : DARK,
      align: "right",
      width: half,
    });
    if (i < contactRows.length - 1) rect(page, col2X, ry + 26, half, 0.5, HAIRLINE);
  });

  // 10. Divider 2
  const profileBottom = detY + 20 + Math.max(profileRows.length, contactRows.length) * ROW;
  const div2Y = profileBottom + 14;
  rect(page, PAD, div2Y, COL, 1, BORDER);

  // 11. Standard terms panel
  const termsY = div2Y + 18;
  const termsH = 204;
  const tPad = 20;
  const tHalfW = COL / 2 - tPad * 2;
  const tLeft = PAD + tPad;
  const tRight = PAD + COL / 2 + tPad;

  rect(page, PAD, termsY, COL, termsH, DARK);
  rect(page, PAD, termsY, COL, 3, GOLD);

  drawText(page, "DELIVERY & REVISIONS", {
    x: tLeft,
    top: termsY + 16,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
  });
  const leftTerms: [string, string][] = [
    ["Turnaround", "5–7 business days"],
    ["Revisions", "2 rounds included per deliverable"],
    ["Approval", "Content shared before going live"],
    ["Brief required", "Written brief needed to proceed"],
  ];
  leftTerms.forEach(([label, value], i) => {
    const ty = termsY + 36 + i * 38;
    drawText(page, label, { x: tLeft, top: ty, size: 8.5, font: reg, color: GRAY });
    drawText(page, value, { x: tLeft, top: ty + 13, size: 9.5, font: bold, color: WHITE });
  });

  drawText(page, "USAGE & PAYMENT", {
    x: tRight,
    top: termsY + 16,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
  });
  const rightTerms: [string, string][] = [
    ["Usage rights", "6 months (standard) / 12 months (premium)"],
    ["Gifted products", "Additional to the quoted rate"],
    ["Exclusivity", "Premium rate only — agreed in writing"],
    ["Payment", "50% deposit upfront · 50% on delivery"],
  ];
  rightTerms.forEach(([label, value], i) => {
    const ty = termsY + 36 + i * 38;
    drawText(page, label, { x: tRight, top: ty, size: 8.5, font: reg, color: GRAY });
    for (const [li, line] of wrap(bold, value, 9.5, tHalfW).entries()) {
      drawText(page, line, {
        x: tRight,
        top: ty + 13 + li * 12,
        size: 9.5,
        font: bold,
        color: WHITE,
      });
    }
  });

  // 12. Engagement advantage panel
  const erPanelY = termsY + termsH + 18;
  const erPanelH = 124;
  rect(page, PAD, erPanelY, COL, erPanelH, GOLD_TINT, { border: GOLD_BDR });
  rect(page, PAD, erPanelY, 4, erPanelH, GOLD);

  drawText(page, "YOUR ENGAGEMENT ADVANTAGE", {
    x: PAD + 18,
    top: erPanelY + 14,
    size: 7.5,
    font: bold,
    color: GOLD,
    tracking: 1.5,
  });
  drawText(
    page,
    `${d.er || "0"}% ER — ${xSA}× the African average  ·  ${xGlobal}× the global average`,
    {
      x: PAD + 18,
      top: erPanelY + 30,
      size: 13,
      font: bold,
      color: DARK,
    },
  );
  const blurb =
    "Brands pay for engagement, not just reach. Your audience is significantly more engaged than the African average of 3.39% — that means lower cost-per-engaged-viewer for the brand. When they push back on your rate, this document is your evidence.";
  wrap(reg, blurb, 10, COL - 40).forEach((line, i) => {
    drawText(page, line, {
      x: PAD + 18,
      top: erPanelY + 52 + i * 14,
      size: 10,
      font: reg,
      color: GRAY,
    });
  });

  // 13. Footer
  const footerY = 1060;
  rect(page, PAD, footerY - 12, COL, 2, GOLD, { opacity: 0.25 });
  drawText(page, "GENERATED BY RATECARD PRO  ·  NOCHILL PTY LTD", {
    x: PAD,
    top: footerY,
    size: 7.5,
    font: bold,
    color: DARK,
    opacity: 0.5,
    tracking: 1.5,
  });
  if (handle) {
    drawText(page, handle, {
      x: 0,
      top: footerY,
      size: 8,
      font: bold,
      color: GOLD,
      opacity: 0.85,
      align: "right",
      width: W - PAD,
    });
  }

  return doc.save();
}
