/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TaxGuideRouteImport } from './routes/tax-guide'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as StarterkitRouteImport } from './routes/starterkit'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SarsCalculatorRouteImport } from './routes/sars-calculator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentedRouteImport } from './routes/rented'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RateCardRouteImport } from './routes/rate-card'
import { Route as ProvisionalTaxRouteImport } from './routes/provisional-tax'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PositioningRouteImport } from './routes/positioning'
import { Route as OfferBuilderRouteImport } from './routes/offer-builder'
import { Route as NicheClarityRouteImport } from './routes/niche-clarity'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HookGeneratorRouteImport } from './routes/hook-generator'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as CreatorBundleRouteImport } from './routes/creator-bundle'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AlignAccelerateExcelRouteImport } from './routes/align-accelerate-excel'
import { Route as AcceleratorRouteImport } from './routes/accelerator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutFoundationRouteImport } from './routes/checkout.foundation'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicToolEventRouteImport } from './routes/api/public/tool-event'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicRateCardRouteImport } from './routes/api/public/rate-card'
import { Route as ApiPublicProvisionalTaxRouteImport } from './routes/api/public/provisional-tax'
import { Route as ApiPublicPositioningRouteImport } from './routes/api/public/positioning'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicManychatLeadRouteImport } from './routes/api/public/manychat-lead'
import { Route as ApiCronSyncFxRouteImport } from './routes/api/cron/sync-fx'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'
import { Route as AuthenticatedDashboardInnerCircleRouteImport } from './routes/_authenticated/dashboard.inner-circle'
import { Route as AuthenticatedDashboardFoundationKitRouteImport } from './routes/_authenticated/dashboard.foundation-kit'
import { Route as AuthenticatedDashboardCommunityRouteImport } from './routes/_authenticated/dashboard.community'
import { Route as AuthenticatedDashboardAcceleratorRouteImport } from './routes/_authenticated/dashboard.accelerator'
import { Route as AuthenticatedAppsYourAlgorithmRouteImport } from './routes/_authenticated/apps.your-algorithm'
import { Route as AuthenticatedAppsVoicePrintRouteImport } from './routes/_authenticated/apps.voice-print'
import { Route as AuthenticatedAppsTheSendRouteImport } from './routes/_authenticated/apps.the-send'
import { Route as AuthenticatedAppsTheLeakRouteImport } from './routes/_authenticated/apps.the-leak'
import { Route as AuthenticatedAppsTheLadderRouteImport } from './routes/_authenticated/apps.the-ladder'
import { Route as AuthenticatedAppsTeleprompterRouteImport } from './routes/_authenticated/apps.teleprompter'
import { Route as AuthenticatedAppsSeedsPipelineRouteImport } from './routes/_authenticated/apps.seeds-pipeline'
import { Route as AuthenticatedAppsSaleScriptsRouteImport } from './routes/_authenticated/apps.sale-scripts'
import { Route as AuthenticatedAppsRightSideDiagnosticRouteImport } from './routes/_authenticated/apps.right-side-diagnostic'
import { Route as AuthenticatedAppsProofLedgerRouteImport } from './routes/_authenticated/apps.proof-ledger'
import { Route as AuthenticatedAppsPriceDecisionRouteImport } from './routes/_authenticated/apps.price-decision'
import { Route as AuthenticatedAppsPaidsAuditorRouteImport } from './routes/_authenticated/apps.paids-auditor'
import { Route as AuthenticatedAppsOfferBlueprintRouteImport } from './routes/_authenticated/apps.offer-blueprint'
import { Route as AuthenticatedAppsNicheClarityBuilderRouteImport } from './routes/_authenticated/apps.niche-clarity-builder'
import { Route as AuthenticatedAppsMsTsSsRouteImport } from './routes/_authenticated/apps.ms-ts-ss'
import { Route as AuthenticatedAppsMoneySplitRouteImport } from './routes/_authenticated/apps.money-split'
import { Route as AuthenticatedAppsMethodNamerRouteImport } from './routes/_authenticated/apps.method-namer'
import { Route as AuthenticatedAppsLeadMagnetRouteImport } from './routes/_authenticated/apps.lead-magnet'
import { Route as AuthenticatedAppsKnowledgeAuditRouteImport } from './routes/_authenticated/apps.knowledge-audit'
import { Route as AuthenticatedAppsIncomeTrackerRouteImport } from './routes/_authenticated/apps.income-tracker'
import { Route as AuthenticatedAppsHookBankRouteImport } from './routes/_authenticated/apps.hook-bank'
import { Route as AuthenticatedAppsFirstIncomePlannerRouteImport } from './routes/_authenticated/apps.first-income-planner'
import { Route as AuthenticatedAppsFirstFiveEmailsRouteImport } from './routes/_authenticated/apps.first-five-emails'
import { Route as AuthenticatedAppsDaresAssetModelRouteImport } from './routes/_authenticated/apps.dares-asset-model'
import { Route as AuthenticatedAppsConsistencyBlueprintRouteImport } from './routes/_authenticated/apps.consistency-blueprint'
import { Route as AuthenticatedAppsAdjacentThreeRouteImport } from './routes/_authenticated/apps.adjacent-three'
import { Route as AuthenticatedApps4eContentCalendarRouteImport } from './routes/_authenticated/apps.4e-content-calendar'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin.ledger'
import { Route as AuthenticatedAdminIncidentsRouteImport } from './routes/_authenticated/admin.incidents'
import { Route as AuthenticatedAdminImportContactsRouteImport } from './routes/_authenticated/admin.import-contacts'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin.contacts'
import { Route as AuthenticatedLearnSlugIndexRouteImport } from './routes/_authenticated/learn.$slug.index'
import { Route as ApiEmailQueueProcessRouteImport } from './routes/api/email/queue/process'
import { Route as ApiEmailAuthWebhookRouteImport } from './routes/api/email/auth/webhook'
import { Route as ApiEmailAuthPreviewRouteImport } from './routes/api/email/auth/preview'
import { Route as AuthenticatedLearnSlugLessonSlugRouteImport } from './routes/_authenticated/learn.$slug.$lessonSlug'
import { Route as AuthenticatedDashboardProductsPaidRouteImport } from './routes/_authenticated/dashboard.products.paid'
import { Route as AuthenticatedDashboardProductsFreeRouteImport } from './routes/_authenticated/dashboard.products.free'
import { Route as AuthenticatedAdminCurriculumProductSlugRouteImport } from './routes/_authenticated/admin.curriculum.$productSlug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxGuideRoute = TaxGuideRouteImport.update({
  id: '/tax-guide',
  path: '/tax-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterkitRoute = StarterkitRouteImport.update({
  id: '/starterkit',
  path: '/starterkit',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SarsCalculatorRoute = SarsCalculatorRouteImport.update({
  id: '/sars-calculator',
  path: '/sars-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentedRoute = RentedRouteImport.update({
  id: '/rented',
  path: '/rented',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardRoute = RateCardRouteImport.update({
  id: '/rate-card',
  path: '/rate-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvisionalTaxRoute = ProvisionalTaxRouteImport.update({
  id: '/provisional-tax',
  path: '/provisional-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PositioningRoute = PositioningRouteImport.update({
  id: '/positioning',
  path: '/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferBuilderRoute = OfferBuilderRouteImport.update({
  id: '/offer-builder',
  path: '/offer-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const NicheClarityRoute = NicheClarityRouteImport.update({
  id: '/niche-clarity',
  path: '/niche-clarity',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HookGeneratorRoute = HookGeneratorRouteImport.update({
  id: '/hook-generator',
  path: '/hook-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorBundleRoute = CreatorBundleRouteImport.update({
  id: '/creator-bundle',
  path: '/creator-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignAccelerateExcelRoute = AlignAccelerateExcelRouteImport.update({
  id: '/align-accelerate-excel',
  path: '/align-accelerate-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorRoute = AcceleratorRouteImport.update({
  id: '/accelerator',
  path: '/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFoundationRoute = CheckoutFoundationRouteImport.update({
  id: '/checkout/foundation',
  path: '/checkout/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicToolEventRoute = ApiPublicToolEventRouteImport.update({
  id: '/api/public/tool-event',
  path: '/api/public/tool-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRateCardRoute = ApiPublicRateCardRouteImport.update({
  id: '/api/public/rate-card',
  path: '/api/public/rate-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProvisionalTaxRoute = ApiPublicProvisionalTaxRouteImport.update({
  id: '/api/public/provisional-tax',
  path: '/api/public/provisional-tax',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPositioningRoute = ApiPublicPositioningRouteImport.update({
  id: '/api/public/positioning',
  path: '/api/public/positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicManychatLeadRoute = ApiPublicManychatLeadRouteImport.update({
  id: '/api/public/manychat-lead',
  path: '/api/public/manychat-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncFxRoute = ApiCronSyncFxRouteImport.update({
  id: '/api/cron/sync-fx',
  path: '/api/cron/sync-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedDashboardInnerCircleRoute =
  AuthenticatedDashboardInnerCircleRouteImport.update({
    id: '/inner-circle',
    path: '/inner-circle',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFoundationKitRoute =
  AuthenticatedDashboardFoundationKitRouteImport.update({
    id: '/foundation-kit',
    path: '/foundation-kit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommunityRoute =
  AuthenticatedDashboardCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAcceleratorRoute =
  AuthenticatedDashboardAcceleratorRouteImport.update({
    id: '/accelerator',
    path: '/accelerator',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAppsYourAlgorithmRoute =
  AuthenticatedAppsYourAlgorithmRouteImport.update({
    id: '/apps/your-algorithm',
    path: '/apps/your-algorithm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsVoicePrintRoute =
  AuthenticatedAppsVoicePrintRouteImport.update({
    id: '/apps/voice-print',
    path: '/apps/voice-print',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsTheSendRoute =
  AuthenticatedAppsTheSendRouteImport.update({
    id: '/apps/the-send',
    path: '/apps/the-send',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsTheLeakRoute =
  AuthenticatedAppsTheLeakRouteImport.update({
    id: '/apps/the-leak',
    path: '/apps/the-leak',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsTheLadderRoute =
  AuthenticatedAppsTheLadderRouteImport.update({
    id: '/apps/the-ladder',
    path: '/apps/the-ladder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsTeleprompterRoute =
  AuthenticatedAppsTeleprompterRouteImport.update({
    id: '/apps/teleprompter',
    path: '/apps/teleprompter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsSeedsPipelineRoute =
  AuthenticatedAppsSeedsPipelineRouteImport.update({
    id: '/apps/seeds-pipeline',
    path: '/apps/seeds-pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsSaleScriptsRoute =
  AuthenticatedAppsSaleScriptsRouteImport.update({
    id: '/apps/sale-scripts',
    path: '/apps/sale-scripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsRightSideDiagnosticRoute =
  AuthenticatedAppsRightSideDiagnosticRouteImport.update({
    id: '/apps/right-side-diagnostic',
    path: '/apps/right-side-diagnostic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsProofLedgerRoute =
  AuthenticatedAppsProofLedgerRouteImport.update({
    id: '/apps/proof-ledger',
    path: '/apps/proof-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsPriceDecisionRoute =
  AuthenticatedAppsPriceDecisionRouteImport.update({
    id: '/apps/price-decision',
    path: '/apps/price-decision',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsPaidsAuditorRoute =
  AuthenticatedAppsPaidsAuditorRouteImport.update({
    id: '/apps/paids-auditor',
    path: '/apps/paids-auditor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsOfferBlueprintRoute =
  AuthenticatedAppsOfferBlueprintRouteImport.update({
    id: '/apps/offer-blueprint',
    path: '/apps/offer-blueprint',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsNicheClarityBuilderRoute =
  AuthenticatedAppsNicheClarityBuilderRouteImport.update({
    id: '/apps/niche-clarity-builder',
    path: '/apps/niche-clarity-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsMsTsSsRoute = AuthenticatedAppsMsTsSsRouteImport.update({
  id: '/apps/ms-ts-ss',
  path: '/apps/ms-ts-ss',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsMoneySplitRoute =
  AuthenticatedAppsMoneySplitRouteImport.update({
    id: '/apps/money-split',
    path: '/apps/money-split',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsMethodNamerRoute =
  AuthenticatedAppsMethodNamerRouteImport.update({
    id: '/apps/method-namer',
    path: '/apps/method-namer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsLeadMagnetRoute =
  AuthenticatedAppsLeadMagnetRouteImport.update({
    id: '/apps/lead-magnet',
    path: '/apps/lead-magnet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsKnowledgeAuditRoute =
  AuthenticatedAppsKnowledgeAuditRouteImport.update({
    id: '/apps/knowledge-audit',
    path: '/apps/knowledge-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsIncomeTrackerRoute =
  AuthenticatedAppsIncomeTrackerRouteImport.update({
    id: '/apps/income-tracker',
    path: '/apps/income-tracker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsHookBankRoute =
  AuthenticatedAppsHookBankRouteImport.update({
    id: '/apps/hook-bank',
    path: '/apps/hook-bank',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsFirstIncomePlannerRoute =
  AuthenticatedAppsFirstIncomePlannerRouteImport.update({
    id: '/apps/first-income-planner',
    path: '/apps/first-income-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsFirstFiveEmailsRoute =
  AuthenticatedAppsFirstFiveEmailsRouteImport.update({
    id: '/apps/first-five-emails',
    path: '/apps/first-five-emails',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsDaresAssetModelRoute =
  AuthenticatedAppsDaresAssetModelRouteImport.update({
    id: '/apps/dares-asset-model',
    path: '/apps/dares-asset-model',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsConsistencyBlueprintRoute =
  AuthenticatedAppsConsistencyBlueprintRouteImport.update({
    id: '/apps/consistency-blueprint',
    path: '/apps/consistency-blueprint',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsAdjacentThreeRoute =
  AuthenticatedAppsAdjacentThreeRouteImport.update({
    id: '/apps/adjacent-three',
    path: '/apps/adjacent-three',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApps4eContentCalendarRoute =
  AuthenticatedApps4eContentCalendarRouteImport.update({
    id: '/apps/4e-content-calendar',
    path: '/apps/4e-content-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncidentsRoute =
  AuthenticatedAdminIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportContactsRoute =
  AuthenticatedAdminImportContactsRouteImport.update({
    id: '/import-contacts',
    path: '/import-contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnSlugIndexRoute =
  AuthenticatedLearnSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnSlugRoute,
  } as any)
const ApiEmailQueueProcessRoute = ApiEmailQueueProcessRouteImport.update({
  id: '/api/email/queue/process',
  path: '/api/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthWebhookRoute = ApiEmailAuthWebhookRouteImport.update({
  id: '/api/email/auth/webhook',
  path: '/api/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthPreviewRoute = ApiEmailAuthPreviewRouteImport.update({
  id: '/api/email/auth/preview',
  path: '/api/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnSlugLessonSlugRoute =
  AuthenticatedLearnSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AuthenticatedLearnSlugRoute,
  } as any)
const AuthenticatedDashboardProductsPaidRoute =
  AuthenticatedDashboardProductsPaidRouteImport.update({
    id: '/products/paid',
    path: '/products/paid',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsFreeRoute =
  AuthenticatedDashboardProductsFreeRouteImport.update({
    id: '/products/free',
    path: '/products/free',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminCurriculumProductSlugRoute =
  AuthenticatedAdminCurriculumProductSlugRouteImport.update({
    id: '/curriculum/$productSlug',
    path: '/curriculum/$productSlug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/creator-bundle': typeof CreatorBundleRoute
  '/foundation': typeof FoundationRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/positioning': typeof PositioningRoute
  '/privacy': typeof PrivacyRoute
  '/provisional-tax': typeof ProvisionalTaxRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rented': typeof RentedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/starterkit': typeof StarterkitRoute
  '/tax': typeof TaxRoute
  '/tax-guide': typeof TaxGuideRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/checkout/foundation': typeof CheckoutFoundationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/apps/adjacent-three': typeof AuthenticatedAppsAdjacentThreeRoute
  '/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/apps/first-five-emails': typeof AuthenticatedAppsFirstFiveEmailsRoute
  '/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/apps/hook-bank': typeof AuthenticatedAppsHookBankRoute
  '/apps/income-tracker': typeof AuthenticatedAppsIncomeTrackerRoute
  '/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/apps/lead-magnet': typeof AuthenticatedAppsLeadMagnetRoute
  '/apps/method-namer': typeof AuthenticatedAppsMethodNamerRoute
  '/apps/money-split': typeof AuthenticatedAppsMoneySplitRoute
  '/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/apps/offer-blueprint': typeof AuthenticatedAppsOfferBlueprintRoute
  '/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/apps/price-decision': typeof AuthenticatedAppsPriceDecisionRoute
  '/apps/proof-ledger': typeof AuthenticatedAppsProofLedgerRoute
  '/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/apps/sale-scripts': typeof AuthenticatedAppsSaleScriptsRoute
  '/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/apps/teleprompter': typeof AuthenticatedAppsTeleprompterRoute
  '/apps/the-ladder': typeof AuthenticatedAppsTheLadderRoute
  '/apps/the-leak': typeof AuthenticatedAppsTheLeakRoute
  '/apps/the-send': typeof AuthenticatedAppsTheSendRoute
  '/apps/voice-print': typeof AuthenticatedAppsVoicePrintRoute
  '/apps/your-algorithm': typeof AuthenticatedAppsYourAlgorithmRoute
  '/dashboard/accelerator': typeof AuthenticatedDashboardAcceleratorRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRouteWithChildren
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/manychat-lead': typeof ApiPublicManychatLeadRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/positioning': typeof ApiPublicPositioningRoute
  '/api/public/provisional-tax': typeof ApiPublicProvisionalTaxRoute
  '/api/public/rate-card': typeof ApiPublicRateCardRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tool-event': typeof ApiPublicToolEventRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/learn/$slug/': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/creator-bundle': typeof CreatorBundleRoute
  '/foundation': typeof FoundationRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/positioning': typeof PositioningRoute
  '/privacy': typeof PrivacyRoute
  '/provisional-tax': typeof ProvisionalTaxRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rented': typeof RentedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/starterkit': typeof StarterkitRoute
  '/tax': typeof TaxRoute
  '/tax-guide': typeof TaxGuideRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout/foundation': typeof CheckoutFoundationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/apps/adjacent-three': typeof AuthenticatedAppsAdjacentThreeRoute
  '/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/apps/first-five-emails': typeof AuthenticatedAppsFirstFiveEmailsRoute
  '/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/apps/hook-bank': typeof AuthenticatedAppsHookBankRoute
  '/apps/income-tracker': typeof AuthenticatedAppsIncomeTrackerRoute
  '/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/apps/lead-magnet': typeof AuthenticatedAppsLeadMagnetRoute
  '/apps/method-namer': typeof AuthenticatedAppsMethodNamerRoute
  '/apps/money-split': typeof AuthenticatedAppsMoneySplitRoute
  '/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/apps/offer-blueprint': typeof AuthenticatedAppsOfferBlueprintRoute
  '/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/apps/price-decision': typeof AuthenticatedAppsPriceDecisionRoute
  '/apps/proof-ledger': typeof AuthenticatedAppsProofLedgerRoute
  '/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/apps/sale-scripts': typeof AuthenticatedAppsSaleScriptsRoute
  '/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/apps/teleprompter': typeof AuthenticatedAppsTeleprompterRoute
  '/apps/the-ladder': typeof AuthenticatedAppsTheLadderRoute
  '/apps/the-leak': typeof AuthenticatedAppsTheLeakRoute
  '/apps/the-send': typeof AuthenticatedAppsTheSendRoute
  '/apps/voice-print': typeof AuthenticatedAppsVoicePrintRoute
  '/apps/your-algorithm': typeof AuthenticatedAppsYourAlgorithmRoute
  '/dashboard/accelerator': typeof AuthenticatedDashboardAcceleratorRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/manychat-lead': typeof ApiPublicManychatLeadRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/positioning': typeof ApiPublicPositioningRoute
  '/api/public/provisional-tax': typeof ApiPublicProvisionalTaxRoute
  '/api/public/rate-card': typeof ApiPublicRateCardRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tool-event': typeof ApiPublicToolEventRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/creator-bundle': typeof CreatorBundleRoute
  '/foundation': typeof FoundationRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/positioning': typeof PositioningRoute
  '/privacy': typeof PrivacyRoute
  '/provisional-tax': typeof ProvisionalTaxRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/rented': typeof RentedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/starterkit': typeof StarterkitRoute
  '/tax': typeof TaxRoute
  '/tax-guide': typeof TaxGuideRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/checkout/foundation': typeof CheckoutFoundationRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/_authenticated/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/_authenticated/apps/adjacent-three': typeof AuthenticatedAppsAdjacentThreeRoute
  '/_authenticated/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/_authenticated/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/_authenticated/apps/first-five-emails': typeof AuthenticatedAppsFirstFiveEmailsRoute
  '/_authenticated/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/_authenticated/apps/hook-bank': typeof AuthenticatedAppsHookBankRoute
  '/_authenticated/apps/income-tracker': typeof AuthenticatedAppsIncomeTrackerRoute
  '/_authenticated/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/_authenticated/apps/lead-magnet': typeof AuthenticatedAppsLeadMagnetRoute
  '/_authenticated/apps/method-namer': typeof AuthenticatedAppsMethodNamerRoute
  '/_authenticated/apps/money-split': typeof AuthenticatedAppsMoneySplitRoute
  '/_authenticated/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/_authenticated/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/_authenticated/apps/offer-blueprint': typeof AuthenticatedAppsOfferBlueprintRoute
  '/_authenticated/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/_authenticated/apps/price-decision': typeof AuthenticatedAppsPriceDecisionRoute
  '/_authenticated/apps/proof-ledger': typeof AuthenticatedAppsProofLedgerRoute
  '/_authenticated/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/_authenticated/apps/sale-scripts': typeof AuthenticatedAppsSaleScriptsRoute
  '/_authenticated/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/_authenticated/apps/teleprompter': typeof AuthenticatedAppsTeleprompterRoute
  '/_authenticated/apps/the-ladder': typeof AuthenticatedAppsTheLadderRoute
  '/_authenticated/apps/the-leak': typeof AuthenticatedAppsTheLeakRoute
  '/_authenticated/apps/the-send': typeof AuthenticatedAppsTheSendRoute
  '/_authenticated/apps/voice-print': typeof AuthenticatedAppsVoicePrintRoute
  '/_authenticated/apps/your-algorithm': typeof AuthenticatedAppsYourAlgorithmRoute
  '/_authenticated/dashboard/accelerator': typeof AuthenticatedDashboardAcceleratorRoute
  '/_authenticated/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/_authenticated/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/_authenticated/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRouteWithChildren
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/manychat-lead': typeof ApiPublicManychatLeadRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/positioning': typeof ApiPublicPositioningRoute
  '/api/public/provisional-tax': typeof ApiPublicProvisionalTaxRoute
  '/api/public/rate-card': typeof ApiPublicRateCardRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tool-event': typeof ApiPublicToolEventRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/_authenticated/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/_authenticated/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/_authenticated/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/_authenticated/learn/$slug/': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accelerator'
    | '/align-accelerate-excel'
    | '/apply'
    | '/cart'
    | '/contact'
    | '/creator-bundle'
    | '/foundation'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/positioning'
    | '/privacy'
    | '/provisional-tax'
    | '/rate-card'
    | '/refund-policy'
    | '/rented'
    | '/reset-password'
    | '/sars-calculator'
    | '/search'
    | '/signup'
    | '/starterkit'
    | '/tax'
    | '/tax-guide'
    | '/terms'
    | '/tools'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/checkout/foundation'
    | '/checkout/success'
    | '/products/$slug'
    | '/products/'
    | '/admin/contacts'
    | '/admin/import-contacts'
    | '/admin/incidents'
    | '/admin/ledger'
    | '/admin/products'
    | '/admin/tools'
    | '/apps/4e-content-calendar'
    | '/apps/adjacent-three'
    | '/apps/consistency-blueprint'
    | '/apps/dares-asset-model'
    | '/apps/first-five-emails'
    | '/apps/first-income-planner'
    | '/apps/hook-bank'
    | '/apps/income-tracker'
    | '/apps/knowledge-audit'
    | '/apps/lead-magnet'
    | '/apps/method-namer'
    | '/apps/money-split'
    | '/apps/ms-ts-ss'
    | '/apps/niche-clarity-builder'
    | '/apps/offer-blueprint'
    | '/apps/paids-auditor'
    | '/apps/price-decision'
    | '/apps/proof-ledger'
    | '/apps/right-side-diagnostic'
    | '/apps/sale-scripts'
    | '/apps/seeds-pipeline'
    | '/apps/teleprompter'
    | '/apps/the-ladder'
    | '/apps/the-leak'
    | '/apps/the-send'
    | '/apps/voice-print'
    | '/apps/your-algorithm'
    | '/dashboard/accelerator'
    | '/dashboard/community'
    | '/dashboard/foundation-kit'
    | '/dashboard/inner-circle'
    | '/learn/$slug'
    | '/api/cron/sync-fx'
    | '/api/public/manychat-lead'
    | '/api/public/paystack-webhook'
    | '/api/public/positioning'
    | '/api/public/provisional-tax'
    | '/api/public/rate-card'
    | '/api/public/stripe-webhook'
    | '/api/public/tool-event'
    | '/admin/'
    | '/dashboard/'
    | '/learn/'
    | '/admin/curriculum/$productSlug'
    | '/dashboard/products/free'
    | '/dashboard/products/paid'
    | '/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/learn/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accelerator'
    | '/align-accelerate-excel'
    | '/apply'
    | '/cart'
    | '/contact'
    | '/creator-bundle'
    | '/foundation'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/positioning'
    | '/privacy'
    | '/provisional-tax'
    | '/rate-card'
    | '/refund-policy'
    | '/rented'
    | '/reset-password'
    | '/sars-calculator'
    | '/search'
    | '/signup'
    | '/starterkit'
    | '/tax'
    | '/tax-guide'
    | '/terms'
    | '/tools'
    | '/account'
    | '/checkout/foundation'
    | '/checkout/success'
    | '/products/$slug'
    | '/products'
    | '/admin/contacts'
    | '/admin/import-contacts'
    | '/admin/incidents'
    | '/admin/ledger'
    | '/admin/products'
    | '/admin/tools'
    | '/apps/4e-content-calendar'
    | '/apps/adjacent-three'
    | '/apps/consistency-blueprint'
    | '/apps/dares-asset-model'
    | '/apps/first-five-emails'
    | '/apps/first-income-planner'
    | '/apps/hook-bank'
    | '/apps/income-tracker'
    | '/apps/knowledge-audit'
    | '/apps/lead-magnet'
    | '/apps/method-namer'
    | '/apps/money-split'
    | '/apps/ms-ts-ss'
    | '/apps/niche-clarity-builder'
    | '/apps/offer-blueprint'
    | '/apps/paids-auditor'
    | '/apps/price-decision'
    | '/apps/proof-ledger'
    | '/apps/right-side-diagnostic'
    | '/apps/sale-scripts'
    | '/apps/seeds-pipeline'
    | '/apps/teleprompter'
    | '/apps/the-ladder'
    | '/apps/the-leak'
    | '/apps/the-send'
    | '/apps/voice-print'
    | '/apps/your-algorithm'
    | '/dashboard/accelerator'
    | '/dashboard/community'
    | '/dashboard/foundation-kit'
    | '/dashboard/inner-circle'
    | '/api/cron/sync-fx'
    | '/api/public/manychat-lead'
    | '/api/public/paystack-webhook'
    | '/api/public/positioning'
    | '/api/public/provisional-tax'
    | '/api/public/rate-card'
    | '/api/public/stripe-webhook'
    | '/api/public/tool-event'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/admin/curriculum/$productSlug'
    | '/dashboard/products/free'
    | '/dashboard/products/paid'
    | '/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accelerator'
    | '/align-accelerate-excel'
    | '/apply'
    | '/cart'
    | '/contact'
    | '/creator-bundle'
    | '/foundation'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/positioning'
    | '/privacy'
    | '/provisional-tax'
    | '/rate-card'
    | '/refund-policy'
    | '/rented'
    | '/reset-password'
    | '/sars-calculator'
    | '/search'
    | '/signup'
    | '/starterkit'
    | '/tax'
    | '/tax-guide'
    | '/terms'
    | '/tools'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/checkout/foundation'
    | '/checkout/success'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/import-contacts'
    | '/_authenticated/admin/incidents'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/tools'
    | '/_authenticated/apps/4e-content-calendar'
    | '/_authenticated/apps/adjacent-three'
    | '/_authenticated/apps/consistency-blueprint'
    | '/_authenticated/apps/dares-asset-model'
    | '/_authenticated/apps/first-five-emails'
    | '/_authenticated/apps/first-income-planner'
    | '/_authenticated/apps/hook-bank'
    | '/_authenticated/apps/income-tracker'
    | '/_authenticated/apps/knowledge-audit'
    | '/_authenticated/apps/lead-magnet'
    | '/_authenticated/apps/method-namer'
    | '/_authenticated/apps/money-split'
    | '/_authenticated/apps/ms-ts-ss'
    | '/_authenticated/apps/niche-clarity-builder'
    | '/_authenticated/apps/offer-blueprint'
    | '/_authenticated/apps/paids-auditor'
    | '/_authenticated/apps/price-decision'
    | '/_authenticated/apps/proof-ledger'
    | '/_authenticated/apps/right-side-diagnostic'
    | '/_authenticated/apps/sale-scripts'
    | '/_authenticated/apps/seeds-pipeline'
    | '/_authenticated/apps/teleprompter'
    | '/_authenticated/apps/the-ladder'
    | '/_authenticated/apps/the-leak'
    | '/_authenticated/apps/the-send'
    | '/_authenticated/apps/voice-print'
    | '/_authenticated/apps/your-algorithm'
    | '/_authenticated/dashboard/accelerator'
    | '/_authenticated/dashboard/community'
    | '/_authenticated/dashboard/foundation-kit'
    | '/_authenticated/dashboard/inner-circle'
    | '/_authenticated/learn/$slug'
    | '/api/cron/sync-fx'
    | '/api/public/manychat-lead'
    | '/api/public/paystack-webhook'
    | '/api/public/positioning'
    | '/api/public/provisional-tax'
    | '/api/public/rate-card'
    | '/api/public/stripe-webhook'
    | '/api/public/tool-event'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/learn/'
    | '/_authenticated/admin/curriculum/$productSlug'
    | '/_authenticated/dashboard/products/free'
    | '/_authenticated/dashboard/products/paid'
    | '/_authenticated/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/_authenticated/learn/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceleratorRoute: typeof AcceleratorRoute
  AlignAccelerateExcelRoute: typeof AlignAccelerateExcelRoute
  ApplyRoute: typeof ApplyRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CreatorBundleRoute: typeof CreatorBundleRoute
  FoundationRoute: typeof FoundationRoute
  HookGeneratorRoute: typeof HookGeneratorRoute
  LoginRoute: typeof LoginRoute
  MediaKitRoute: typeof MediaKitRoute
  NicheClarityRoute: typeof NicheClarityRoute
  OfferBuilderRoute: typeof OfferBuilderRoute
  PositioningRoute: typeof PositioningRoute
  PrivacyRoute: typeof PrivacyRoute
  ProvisionalTaxRoute: typeof ProvisionalTaxRoute
  RateCardRoute: typeof RateCardRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RentedRoute: typeof RentedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SarsCalculatorRoute: typeof SarsCalculatorRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  StarterkitRoute: typeof StarterkitRoute
  TaxRoute: typeof TaxRoute
  TaxGuideRoute: typeof TaxGuideRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  CheckoutFoundationRoute: typeof CheckoutFoundationRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiCronSyncFxRoute: typeof ApiCronSyncFxRoute
  ApiPublicManychatLeadRoute: typeof ApiPublicManychatLeadRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicPositioningRoute: typeof ApiPublicPositioningRoute
  ApiPublicProvisionalTaxRoute: typeof ApiPublicProvisionalTaxRoute
  ApiPublicRateCardRoute: typeof ApiPublicRateCardRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicToolEventRoute: typeof ApiPublicToolEventRoute
  ApiEmailAuthPreviewRoute: typeof ApiEmailAuthPreviewRoute
  ApiEmailAuthWebhookRoute: typeof ApiEmailAuthWebhookRoute
  ApiEmailQueueProcessRoute: typeof ApiEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-guide': {
      id: '/tax-guide'
      path: '/tax-guide'
      fullPath: '/tax-guide'
      preLoaderRoute: typeof TaxGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starterkit': {
      id: '/starterkit'
      path: '/starterkit'
      fullPath: '/starterkit'
      preLoaderRoute: typeof StarterkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sars-calculator': {
      id: '/sars-calculator'
      path: '/sars-calculator'
      fullPath: '/sars-calculator'
      preLoaderRoute: typeof SarsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rented': {
      id: '/rented'
      path: '/rented'
      fullPath: '/rented'
      preLoaderRoute: typeof RentedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-card': {
      id: '/rate-card'
      path: '/rate-card'
      fullPath: '/rate-card'
      preLoaderRoute: typeof RateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provisional-tax': {
      id: '/provisional-tax'
      path: '/provisional-tax'
      fullPath: '/provisional-tax'
      preLoaderRoute: typeof ProvisionalTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positioning': {
      id: '/positioning'
      path: '/positioning'
      fullPath: '/positioning'
      preLoaderRoute: typeof PositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-builder': {
      id: '/offer-builder'
      path: '/offer-builder'
      fullPath: '/offer-builder'
      preLoaderRoute: typeof OfferBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niche-clarity': {
      id: '/niche-clarity'
      path: '/niche-clarity'
      fullPath: '/niche-clarity'
      preLoaderRoute: typeof NicheClarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hook-generator': {
      id: '/hook-generator'
      path: '/hook-generator'
      fullPath: '/hook-generator'
      preLoaderRoute: typeof HookGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-bundle': {
      id: '/creator-bundle'
      path: '/creator-bundle'
      fullPath: '/creator-bundle'
      preLoaderRoute: typeof CreatorBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align-accelerate-excel': {
      id: '/align-accelerate-excel'
      path: '/align-accelerate-excel'
      fullPath: '/align-accelerate-excel'
      preLoaderRoute: typeof AlignAccelerateExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerator': {
      id: '/accelerator'
      path: '/accelerator'
      fullPath: '/accelerator'
      preLoaderRoute: typeof AcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/foundation': {
      id: '/checkout/foundation'
      path: '/checkout/foundation'
      fullPath: '/checkout/foundation'
      preLoaderRoute: typeof CheckoutFoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/tool-event': {
      id: '/api/public/tool-event'
      path: '/api/public/tool-event'
      fullPath: '/api/public/tool-event'
      preLoaderRoute: typeof ApiPublicToolEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rate-card': {
      id: '/api/public/rate-card'
      path: '/api/public/rate-card'
      fullPath: '/api/public/rate-card'
      preLoaderRoute: typeof ApiPublicRateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provisional-tax': {
      id: '/api/public/provisional-tax'
      path: '/api/public/provisional-tax'
      fullPath: '/api/public/provisional-tax'
      preLoaderRoute: typeof ApiPublicProvisionalTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/positioning': {
      id: '/api/public/positioning'
      path: '/api/public/positioning'
      fullPath: '/api/public/positioning'
      preLoaderRoute: typeof ApiPublicPositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manychat-lead': {
      id: '/api/public/manychat-lead'
      path: '/api/public/manychat-lead'
      fullPath: '/api/public/manychat-lead'
      preLoaderRoute: typeof ApiPublicManychatLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-fx': {
      id: '/api/cron/sync-fx'
      path: '/api/cron/sync-fx'
      fullPath: '/api/cron/sync-fx'
      preLoaderRoute: typeof ApiCronSyncFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/dashboard/inner-circle': {
      id: '/_authenticated/dashboard/inner-circle'
      path: '/inner-circle'
      fullPath: '/dashboard/inner-circle'
      preLoaderRoute: typeof AuthenticatedDashboardInnerCircleRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/foundation-kit': {
      id: '/_authenticated/dashboard/foundation-kit'
      path: '/foundation-kit'
      fullPath: '/dashboard/foundation-kit'
      preLoaderRoute: typeof AuthenticatedDashboardFoundationKitRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/community': {
      id: '/_authenticated/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AuthenticatedDashboardCommunityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/accelerator': {
      id: '/_authenticated/dashboard/accelerator'
      path: '/accelerator'
      fullPath: '/dashboard/accelerator'
      preLoaderRoute: typeof AuthenticatedDashboardAcceleratorRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/apps/your-algorithm': {
      id: '/_authenticated/apps/your-algorithm'
      path: '/apps/your-algorithm'
      fullPath: '/apps/your-algorithm'
      preLoaderRoute: typeof AuthenticatedAppsYourAlgorithmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/voice-print': {
      id: '/_authenticated/apps/voice-print'
      path: '/apps/voice-print'
      fullPath: '/apps/voice-print'
      preLoaderRoute: typeof AuthenticatedAppsVoicePrintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/the-send': {
      id: '/_authenticated/apps/the-send'
      path: '/apps/the-send'
      fullPath: '/apps/the-send'
      preLoaderRoute: typeof AuthenticatedAppsTheSendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/the-leak': {
      id: '/_authenticated/apps/the-leak'
      path: '/apps/the-leak'
      fullPath: '/apps/the-leak'
      preLoaderRoute: typeof AuthenticatedAppsTheLeakRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/the-ladder': {
      id: '/_authenticated/apps/the-ladder'
      path: '/apps/the-ladder'
      fullPath: '/apps/the-ladder'
      preLoaderRoute: typeof AuthenticatedAppsTheLadderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/teleprompter': {
      id: '/_authenticated/apps/teleprompter'
      path: '/apps/teleprompter'
      fullPath: '/apps/teleprompter'
      preLoaderRoute: typeof AuthenticatedAppsTeleprompterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/seeds-pipeline': {
      id: '/_authenticated/apps/seeds-pipeline'
      path: '/apps/seeds-pipeline'
      fullPath: '/apps/seeds-pipeline'
      preLoaderRoute: typeof AuthenticatedAppsSeedsPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/sale-scripts': {
      id: '/_authenticated/apps/sale-scripts'
      path: '/apps/sale-scripts'
      fullPath: '/apps/sale-scripts'
      preLoaderRoute: typeof AuthenticatedAppsSaleScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/right-side-diagnostic': {
      id: '/_authenticated/apps/right-side-diagnostic'
      path: '/apps/right-side-diagnostic'
      fullPath: '/apps/right-side-diagnostic'
      preLoaderRoute: typeof AuthenticatedAppsRightSideDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/proof-ledger': {
      id: '/_authenticated/apps/proof-ledger'
      path: '/apps/proof-ledger'
      fullPath: '/apps/proof-ledger'
      preLoaderRoute: typeof AuthenticatedAppsProofLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/price-decision': {
      id: '/_authenticated/apps/price-decision'
      path: '/apps/price-decision'
      fullPath: '/apps/price-decision'
      preLoaderRoute: typeof AuthenticatedAppsPriceDecisionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/paids-auditor': {
      id: '/_authenticated/apps/paids-auditor'
      path: '/apps/paids-auditor'
      fullPath: '/apps/paids-auditor'
      preLoaderRoute: typeof AuthenticatedAppsPaidsAuditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/offer-blueprint': {
      id: '/_authenticated/apps/offer-blueprint'
      path: '/apps/offer-blueprint'
      fullPath: '/apps/offer-blueprint'
      preLoaderRoute: typeof AuthenticatedAppsOfferBlueprintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/niche-clarity-builder': {
      id: '/_authenticated/apps/niche-clarity-builder'
      path: '/apps/niche-clarity-builder'
      fullPath: '/apps/niche-clarity-builder'
      preLoaderRoute: typeof AuthenticatedAppsNicheClarityBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/ms-ts-ss': {
      id: '/_authenticated/apps/ms-ts-ss'
      path: '/apps/ms-ts-ss'
      fullPath: '/apps/ms-ts-ss'
      preLoaderRoute: typeof AuthenticatedAppsMsTsSsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/money-split': {
      id: '/_authenticated/apps/money-split'
      path: '/apps/money-split'
      fullPath: '/apps/money-split'
      preLoaderRoute: typeof AuthenticatedAppsMoneySplitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/method-namer': {
      id: '/_authenticated/apps/method-namer'
      path: '/apps/method-namer'
      fullPath: '/apps/method-namer'
      preLoaderRoute: typeof AuthenticatedAppsMethodNamerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/lead-magnet': {
      id: '/_authenticated/apps/lead-magnet'
      path: '/apps/lead-magnet'
      fullPath: '/apps/lead-magnet'
      preLoaderRoute: typeof AuthenticatedAppsLeadMagnetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/knowledge-audit': {
      id: '/_authenticated/apps/knowledge-audit'
      path: '/apps/knowledge-audit'
      fullPath: '/apps/knowledge-audit'
      preLoaderRoute: typeof AuthenticatedAppsKnowledgeAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/income-tracker': {
      id: '/_authenticated/apps/income-tracker'
      path: '/apps/income-tracker'
      fullPath: '/apps/income-tracker'
      preLoaderRoute: typeof AuthenticatedAppsIncomeTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/hook-bank': {
      id: '/_authenticated/apps/hook-bank'
      path: '/apps/hook-bank'
      fullPath: '/apps/hook-bank'
      preLoaderRoute: typeof AuthenticatedAppsHookBankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/first-income-planner': {
      id: '/_authenticated/apps/first-income-planner'
      path: '/apps/first-income-planner'
      fullPath: '/apps/first-income-planner'
      preLoaderRoute: typeof AuthenticatedAppsFirstIncomePlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/first-five-emails': {
      id: '/_authenticated/apps/first-five-emails'
      path: '/apps/first-five-emails'
      fullPath: '/apps/first-five-emails'
      preLoaderRoute: typeof AuthenticatedAppsFirstFiveEmailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/dares-asset-model': {
      id: '/_authenticated/apps/dares-asset-model'
      path: '/apps/dares-asset-model'
      fullPath: '/apps/dares-asset-model'
      preLoaderRoute: typeof AuthenticatedAppsDaresAssetModelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/consistency-blueprint': {
      id: '/_authenticated/apps/consistency-blueprint'
      path: '/apps/consistency-blueprint'
      fullPath: '/apps/consistency-blueprint'
      preLoaderRoute: typeof AuthenticatedAppsConsistencyBlueprintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/adjacent-three': {
      id: '/_authenticated/apps/adjacent-three'
      path: '/apps/adjacent-three'
      fullPath: '/apps/adjacent-three'
      preLoaderRoute: typeof AuthenticatedAppsAdjacentThreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/4e-content-calendar': {
      id: '/_authenticated/apps/4e-content-calendar'
      path: '/apps/4e-content-calendar'
      fullPath: '/apps/4e-content-calendar'
      preLoaderRoute: typeof AuthenticatedApps4eContentCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incidents': {
      id: '/_authenticated/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import-contacts': {
      id: '/_authenticated/admin/import-contacts'
      path: '/import-contacts'
      fullPath: '/admin/import-contacts'
      preLoaderRoute: typeof AuthenticatedAdminImportContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/learn/$slug/': {
      id: '/_authenticated/learn/$slug/'
      path: '/'
      fullPath: '/learn/$slug/'
      preLoaderRoute: typeof AuthenticatedLearnSlugIndexRouteImport
      parentRoute: typeof AuthenticatedLearnSlugRoute
    }
    '/api/email/queue/process': {
      id: '/api/email/queue/process'
      path: '/api/email/queue/process'
      fullPath: '/api/email/queue/process'
      preLoaderRoute: typeof ApiEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/webhook': {
      id: '/api/email/auth/webhook'
      path: '/api/email/auth/webhook'
      fullPath: '/api/email/auth/webhook'
      preLoaderRoute: typeof ApiEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/preview': {
      id: '/api/email/auth/preview'
      path: '/api/email/auth/preview'
      fullPath: '/api/email/auth/preview'
      preLoaderRoute: typeof ApiEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$slug/$lessonSlug': {
      id: '/_authenticated/learn/$slug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/$slug/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedLearnSlugLessonSlugRouteImport
      parentRoute: typeof AuthenticatedLearnSlugRoute
    }
    '/_authenticated/dashboard/products/paid': {
      id: '/_authenticated/dashboard/products/paid'
      path: '/products/paid'
      fullPath: '/dashboard/products/paid'
      preLoaderRoute: typeof AuthenticatedDashboardProductsPaidRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products/free': {
      id: '/_authenticated/dashboard/products/free'
      path: '/products/free'
      fullPath: '/dashboard/products/free'
      preLoaderRoute: typeof AuthenticatedDashboardProductsFreeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/curriculum/$productSlug': {
      id: '/_authenticated/admin/curriculum/$productSlug'
      path: '/curriculum/$productSlug'
      fullPath: '/admin/curriculum/$productSlug'
      preLoaderRoute: typeof AuthenticatedAdminCurriculumProductSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminImportContactsRoute: typeof AuthenticatedAdminImportContactsRoute
  AuthenticatedAdminIncidentsRoute: typeof AuthenticatedAdminIncidentsRoute
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCurriculumProductSlugRoute: typeof AuthenticatedAdminCurriculumProductSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminImportContactsRoute: AuthenticatedAdminImportContactsRoute,
  AuthenticatedAdminIncidentsRoute: AuthenticatedAdminIncidentsRoute,
  AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCurriculumProductSlugRoute:
    AuthenticatedAdminCurriculumProductSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAcceleratorRoute: typeof AuthenticatedDashboardAcceleratorRoute
  AuthenticatedDashboardCommunityRoute: typeof AuthenticatedDashboardCommunityRoute
  AuthenticatedDashboardFoundationKitRoute: typeof AuthenticatedDashboardFoundationKitRoute
  AuthenticatedDashboardInnerCircleRoute: typeof AuthenticatedDashboardInnerCircleRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardProductsFreeRoute: typeof AuthenticatedDashboardProductsFreeRoute
  AuthenticatedDashboardProductsPaidRoute: typeof AuthenticatedDashboardProductsPaidRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAcceleratorRoute:
      AuthenticatedDashboardAcceleratorRoute,
    AuthenticatedDashboardCommunityRoute: AuthenticatedDashboardCommunityRoute,
    AuthenticatedDashboardFoundationKitRoute:
      AuthenticatedDashboardFoundationKitRoute,
    AuthenticatedDashboardInnerCircleRoute:
      AuthenticatedDashboardInnerCircleRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardProductsFreeRoute:
      AuthenticatedDashboardProductsFreeRoute,
    AuthenticatedDashboardProductsPaidRoute:
      AuthenticatedDashboardProductsPaidRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedLearnSlugRouteChildren {
  AuthenticatedLearnSlugLessonSlugRoute: typeof AuthenticatedLearnSlugLessonSlugRoute
  AuthenticatedLearnSlugIndexRoute: typeof AuthenticatedLearnSlugIndexRoute
}

const AuthenticatedLearnSlugRouteChildren: AuthenticatedLearnSlugRouteChildren =
  {
    AuthenticatedLearnSlugLessonSlugRoute:
      AuthenticatedLearnSlugLessonSlugRoute,
    AuthenticatedLearnSlugIndexRoute: AuthenticatedLearnSlugIndexRoute,
  }

const AuthenticatedLearnSlugRouteWithChildren =
  AuthenticatedLearnSlugRoute._addFileChildren(
    AuthenticatedLearnSlugRouteChildren,
  )

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRouteWithChildren
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRouteWithChildren,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedApps4eContentCalendarRoute: typeof AuthenticatedApps4eContentCalendarRoute
  AuthenticatedAppsAdjacentThreeRoute: typeof AuthenticatedAppsAdjacentThreeRoute
  AuthenticatedAppsConsistencyBlueprintRoute: typeof AuthenticatedAppsConsistencyBlueprintRoute
  AuthenticatedAppsDaresAssetModelRoute: typeof AuthenticatedAppsDaresAssetModelRoute
  AuthenticatedAppsFirstFiveEmailsRoute: typeof AuthenticatedAppsFirstFiveEmailsRoute
  AuthenticatedAppsFirstIncomePlannerRoute: typeof AuthenticatedAppsFirstIncomePlannerRoute
  AuthenticatedAppsHookBankRoute: typeof AuthenticatedAppsHookBankRoute
  AuthenticatedAppsIncomeTrackerRoute: typeof AuthenticatedAppsIncomeTrackerRoute
  AuthenticatedAppsKnowledgeAuditRoute: typeof AuthenticatedAppsKnowledgeAuditRoute
  AuthenticatedAppsLeadMagnetRoute: typeof AuthenticatedAppsLeadMagnetRoute
  AuthenticatedAppsMethodNamerRoute: typeof AuthenticatedAppsMethodNamerRoute
  AuthenticatedAppsMoneySplitRoute: typeof AuthenticatedAppsMoneySplitRoute
  AuthenticatedAppsMsTsSsRoute: typeof AuthenticatedAppsMsTsSsRoute
  AuthenticatedAppsNicheClarityBuilderRoute: typeof AuthenticatedAppsNicheClarityBuilderRoute
  AuthenticatedAppsOfferBlueprintRoute: typeof AuthenticatedAppsOfferBlueprintRoute
  AuthenticatedAppsPaidsAuditorRoute: typeof AuthenticatedAppsPaidsAuditorRoute
  AuthenticatedAppsPriceDecisionRoute: typeof AuthenticatedAppsPriceDecisionRoute
  AuthenticatedAppsProofLedgerRoute: typeof AuthenticatedAppsProofLedgerRoute
  AuthenticatedAppsRightSideDiagnosticRoute: typeof AuthenticatedAppsRightSideDiagnosticRoute
  AuthenticatedAppsSaleScriptsRoute: typeof AuthenticatedAppsSaleScriptsRoute
  AuthenticatedAppsSeedsPipelineRoute: typeof AuthenticatedAppsSeedsPipelineRoute
  AuthenticatedAppsTeleprompterRoute: typeof AuthenticatedAppsTeleprompterRoute
  AuthenticatedAppsTheLadderRoute: typeof AuthenticatedAppsTheLadderRoute
  AuthenticatedAppsTheLeakRoute: typeof AuthenticatedAppsTheLeakRoute
  AuthenticatedAppsTheSendRoute: typeof AuthenticatedAppsTheSendRoute
  AuthenticatedAppsVoicePrintRoute: typeof AuthenticatedAppsVoicePrintRoute
  AuthenticatedAppsYourAlgorithmRoute: typeof AuthenticatedAppsYourAlgorithmRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedApps4eContentCalendarRoute:
    AuthenticatedApps4eContentCalendarRoute,
  AuthenticatedAppsAdjacentThreeRoute: AuthenticatedAppsAdjacentThreeRoute,
  AuthenticatedAppsConsistencyBlueprintRoute:
    AuthenticatedAppsConsistencyBlueprintRoute,
  AuthenticatedAppsDaresAssetModelRoute: AuthenticatedAppsDaresAssetModelRoute,
  AuthenticatedAppsFirstFiveEmailsRoute: AuthenticatedAppsFirstFiveEmailsRoute,
  AuthenticatedAppsFirstIncomePlannerRoute:
    AuthenticatedAppsFirstIncomePlannerRoute,
  AuthenticatedAppsHookBankRoute: AuthenticatedAppsHookBankRoute,
  AuthenticatedAppsIncomeTrackerRoute: AuthenticatedAppsIncomeTrackerRoute,
  AuthenticatedAppsKnowledgeAuditRoute: AuthenticatedAppsKnowledgeAuditRoute,
  AuthenticatedAppsLeadMagnetRoute: AuthenticatedAppsLeadMagnetRoute,
  AuthenticatedAppsMethodNamerRoute: AuthenticatedAppsMethodNamerRoute,
  AuthenticatedAppsMoneySplitRoute: AuthenticatedAppsMoneySplitRoute,
  AuthenticatedAppsMsTsSsRoute: AuthenticatedAppsMsTsSsRoute,
  AuthenticatedAppsNicheClarityBuilderRoute:
    AuthenticatedAppsNicheClarityBuilderRoute,
  AuthenticatedAppsOfferBlueprintRoute: AuthenticatedAppsOfferBlueprintRoute,
  AuthenticatedAppsPaidsAuditorRoute: AuthenticatedAppsPaidsAuditorRoute,
  AuthenticatedAppsPriceDecisionRoute: AuthenticatedAppsPriceDecisionRoute,
  AuthenticatedAppsProofLedgerRoute: AuthenticatedAppsProofLedgerRoute,
  AuthenticatedAppsRightSideDiagnosticRoute:
    AuthenticatedAppsRightSideDiagnosticRoute,
  AuthenticatedAppsSaleScriptsRoute: AuthenticatedAppsSaleScriptsRoute,
  AuthenticatedAppsSeedsPipelineRoute: AuthenticatedAppsSeedsPipelineRoute,
  AuthenticatedAppsTeleprompterRoute: AuthenticatedAppsTeleprompterRoute,
  AuthenticatedAppsTheLadderRoute: AuthenticatedAppsTheLadderRoute,
  AuthenticatedAppsTheLeakRoute: AuthenticatedAppsTheLeakRoute,
  AuthenticatedAppsTheSendRoute: AuthenticatedAppsTheSendRoute,
  AuthenticatedAppsVoicePrintRoute: AuthenticatedAppsVoicePrintRoute,
  AuthenticatedAppsYourAlgorithmRoute: AuthenticatedAppsYourAlgorithmRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceleratorRoute: AcceleratorRoute,
  AlignAccelerateExcelRoute: AlignAccelerateExcelRoute,
  ApplyRoute: ApplyRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CreatorBundleRoute: CreatorBundleRoute,
  FoundationRoute: FoundationRoute,
  HookGeneratorRoute: HookGeneratorRoute,
  LoginRoute: LoginRoute,
  MediaKitRoute: MediaKitRoute,
  NicheClarityRoute: NicheClarityRoute,
  OfferBuilderRoute: OfferBuilderRoute,
  PositioningRoute: PositioningRoute,
  PrivacyRoute: PrivacyRoute,
  ProvisionalTaxRoute: ProvisionalTaxRoute,
  RateCardRoute: RateCardRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RentedRoute: RentedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SarsCalculatorRoute: SarsCalculatorRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  StarterkitRoute: StarterkitRoute,
  TaxRoute: TaxRoute,
  TaxGuideRoute: TaxGuideRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  CheckoutFoundationRoute: CheckoutFoundationRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiCronSyncFxRoute: ApiCronSyncFxRoute,
  ApiPublicManychatLeadRoute: ApiPublicManychatLeadRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicPositioningRoute: ApiPublicPositioningRoute,
  ApiPublicProvisionalTaxRoute: ApiPublicProvisionalTaxRoute,
  ApiPublicRateCardRoute: ApiPublicRateCardRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicToolEventRoute: ApiPublicToolEventRoute,
  ApiEmailAuthPreviewRoute: ApiEmailAuthPreviewRoute,
  ApiEmailAuthWebhookRoute: ApiEmailAuthWebhookRoute,
  ApiEmailQueueProcessRoute: ApiEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
