/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SarsCalculatorRouteImport } from './routes/sars-calculator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RateCardRouteImport } from './routes/rate-card'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfferBuilderRouteImport } from './routes/offer-builder'
import { Route as NicheClarityRouteImport } from './routes/niche-clarity'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HookGeneratorRouteImport } from './routes/hook-generator'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AlignAccelerateExcelRouteImport } from './routes/align-accelerate-excel'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ProductsGardenGardenRouteImport } from './routes/products.garden.$garden'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiCronSyncFxRouteImport } from './routes/api/cron/sync-fx'
import { Route as AuthenticatedLearnSlugRouteImport } from './routes/_authenticated/learn.$slug'
import { Route as AuthenticatedDashboardInnerCircleRouteImport } from './routes/_authenticated/dashboard.inner-circle'
import { Route as AuthenticatedDashboardFoundationKitRouteImport } from './routes/_authenticated/dashboard.foundation-kit'
import { Route as AuthenticatedAppsSeedsPipelineRouteImport } from './routes/_authenticated/apps.seeds-pipeline'
import { Route as AuthenticatedAppsRightSideDiagnosticRouteImport } from './routes/_authenticated/apps.right-side-diagnostic'
import { Route as AuthenticatedAppsPaidsAuditorRouteImport } from './routes/_authenticated/apps.paids-auditor'
import { Route as AuthenticatedAppsNicheClarityBuilderRouteImport } from './routes/_authenticated/apps.niche-clarity-builder'
import { Route as AuthenticatedAppsMsTsSsRouteImport } from './routes/_authenticated/apps.ms-ts-ss'
import { Route as AuthenticatedAppsKnowledgeAuditRouteImport } from './routes/_authenticated/apps.knowledge-audit'
import { Route as AuthenticatedAppsFirstIncomePlannerRouteImport } from './routes/_authenticated/apps.first-income-planner'
import { Route as AuthenticatedAppsDaresAssetModelRouteImport } from './routes/_authenticated/apps.dares-asset-model'
import { Route as AuthenticatedAppsConsistencyBlueprintRouteImport } from './routes/_authenticated/apps.consistency-blueprint'
import { Route as AuthenticatedApps4eContentCalendarRouteImport } from './routes/_authenticated/apps.4e-content-calendar'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin.ledger'
import { Route as AuthenticatedAdminIncidentsRouteImport } from './routes/_authenticated/admin.incidents'
import { Route as AuthenticatedAdminImportContactsRouteImport } from './routes/_authenticated/admin.import-contacts'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin.contacts'
import { Route as AuthenticatedLearnSlugIndexRouteImport } from './routes/_authenticated/learn.$slug.index'
import { Route as ApiEmailQueueProcessRouteImport } from './routes/api/email/queue/process'
import { Route as ApiEmailAuthWebhookRouteImport } from './routes/api/email/auth/webhook'
import { Route as ApiEmailAuthPreviewRouteImport } from './routes/api/email/auth/preview'
import { Route as AuthenticatedLearnSlugLessonSlugRouteImport } from './routes/_authenticated/learn.$slug.$lessonSlug'
import { Route as AuthenticatedDashboardProductsPaidRouteImport } from './routes/_authenticated/dashboard.products.paid'
import { Route as AuthenticatedDashboardProductsFreeRouteImport } from './routes/_authenticated/dashboard.products.free'
import { Route as AuthenticatedAdminCurriculumProductSlugRouteImport } from './routes/_authenticated/admin.curriculum.$productSlug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SarsCalculatorRoute = SarsCalculatorRouteImport.update({
  id: '/sars-calculator',
  path: '/sars-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardRoute = RateCardRouteImport.update({
  id: '/rate-card',
  path: '/rate-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferBuilderRoute = OfferBuilderRouteImport.update({
  id: '/offer-builder',
  path: '/offer-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const NicheClarityRoute = NicheClarityRouteImport.update({
  id: '/niche-clarity',
  path: '/niche-clarity',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HookGeneratorRoute = HookGeneratorRouteImport.update({
  id: '/hook-generator',
  path: '/hook-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignAccelerateExcelRoute = AlignAccelerateExcelRouteImport.update({
  id: '/align-accelerate-excel',
  path: '/align-accelerate-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ProductsGardenGardenRoute = ProductsGardenGardenRouteImport.update({
  id: '/products/garden/$garden',
  path: '/products/garden/$garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSyncFxRoute = ApiCronSyncFxRouteImport.update({
  id: '/api/cron/sync-fx',
  path: '/api/cron/sync-fx',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnSlugRoute = AuthenticatedLearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedLearnRoute,
} as any)
const AuthenticatedDashboardInnerCircleRoute =
  AuthenticatedDashboardInnerCircleRouteImport.update({
    id: '/inner-circle',
    path: '/inner-circle',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFoundationKitRoute =
  AuthenticatedDashboardFoundationKitRouteImport.update({
    id: '/foundation-kit',
    path: '/foundation-kit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAppsSeedsPipelineRoute =
  AuthenticatedAppsSeedsPipelineRouteImport.update({
    id: '/apps/seeds-pipeline',
    path: '/apps/seeds-pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsRightSideDiagnosticRoute =
  AuthenticatedAppsRightSideDiagnosticRouteImport.update({
    id: '/apps/right-side-diagnostic',
    path: '/apps/right-side-diagnostic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsPaidsAuditorRoute =
  AuthenticatedAppsPaidsAuditorRouteImport.update({
    id: '/apps/paids-auditor',
    path: '/apps/paids-auditor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsNicheClarityBuilderRoute =
  AuthenticatedAppsNicheClarityBuilderRouteImport.update({
    id: '/apps/niche-clarity-builder',
    path: '/apps/niche-clarity-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsMsTsSsRoute = AuthenticatedAppsMsTsSsRouteImport.update({
  id: '/apps/ms-ts-ss',
  path: '/apps/ms-ts-ss',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsKnowledgeAuditRoute =
  AuthenticatedAppsKnowledgeAuditRouteImport.update({
    id: '/apps/knowledge-audit',
    path: '/apps/knowledge-audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsFirstIncomePlannerRoute =
  AuthenticatedAppsFirstIncomePlannerRouteImport.update({
    id: '/apps/first-income-planner',
    path: '/apps/first-income-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsDaresAssetModelRoute =
  AuthenticatedAppsDaresAssetModelRouteImport.update({
    id: '/apps/dares-asset-model',
    path: '/apps/dares-asset-model',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsConsistencyBlueprintRoute =
  AuthenticatedAppsConsistencyBlueprintRouteImport.update({
    id: '/apps/consistency-blueprint',
    path: '/apps/consistency-blueprint',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApps4eContentCalendarRoute =
  AuthenticatedApps4eContentCalendarRouteImport.update({
    id: '/apps/4e-content-calendar',
    path: '/apps/4e-content-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncidentsRoute =
  AuthenticatedAdminIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportContactsRoute =
  AuthenticatedAdminImportContactsRouteImport.update({
    id: '/import-contacts',
    path: '/import-contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedLearnSlugIndexRoute =
  AuthenticatedLearnSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLearnSlugRoute,
  } as any)
const ApiEmailQueueProcessRoute = ApiEmailQueueProcessRouteImport.update({
  id: '/api/email/queue/process',
  path: '/api/email/queue/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthWebhookRoute = ApiEmailAuthWebhookRouteImport.update({
  id: '/api/email/auth/webhook',
  path: '/api/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailAuthPreviewRoute = ApiEmailAuthPreviewRouteImport.update({
  id: '/api/email/auth/preview',
  path: '/api/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnSlugLessonSlugRoute =
  AuthenticatedLearnSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AuthenticatedLearnSlugRoute,
  } as any)
const AuthenticatedDashboardProductsPaidRoute =
  AuthenticatedDashboardProductsPaidRouteImport.update({
    id: '/products/paid',
    path: '/products/paid',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProductsFreeRoute =
  AuthenticatedDashboardProductsFreeRouteImport.update({
    id: '/products/free',
    path: '/products/free',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminCurriculumProductSlugRoute =
  AuthenticatedAdminCurriculumProductSlugRouteImport.update({
    id: '/curriculum/$productSlug',
    path: '/curriculum/$productSlug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/learn': typeof AuthenticatedLearnRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugRouteWithChildren
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/products/garden/$garden': typeof ProductsGardenGardenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/learn/$slug/': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/products/garden/$garden': typeof ProductsGardenGardenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/learn/$slug': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/align-accelerate-excel': typeof AlignAccelerateExcelRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/hook-generator': typeof HookGeneratorRoute
  '/login': typeof LoginRoute
  '/media-kit': typeof MediaKitRoute
  '/niche-clarity': typeof NicheClarityRoute
  '/offer-builder': typeof OfferBuilderRoute
  '/privacy': typeof PrivacyRoute
  '/rate-card': typeof RateCardRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sars-calculator': typeof SarsCalculatorRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/learn': typeof AuthenticatedLearnRouteWithChildren
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/import-contacts': typeof AuthenticatedAdminImportContactsRoute
  '/_authenticated/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/apps/4e-content-calendar': typeof AuthenticatedApps4eContentCalendarRoute
  '/_authenticated/apps/consistency-blueprint': typeof AuthenticatedAppsConsistencyBlueprintRoute
  '/_authenticated/apps/dares-asset-model': typeof AuthenticatedAppsDaresAssetModelRoute
  '/_authenticated/apps/first-income-planner': typeof AuthenticatedAppsFirstIncomePlannerRoute
  '/_authenticated/apps/knowledge-audit': typeof AuthenticatedAppsKnowledgeAuditRoute
  '/_authenticated/apps/ms-ts-ss': typeof AuthenticatedAppsMsTsSsRoute
  '/_authenticated/apps/niche-clarity-builder': typeof AuthenticatedAppsNicheClarityBuilderRoute
  '/_authenticated/apps/paids-auditor': typeof AuthenticatedAppsPaidsAuditorRoute
  '/_authenticated/apps/right-side-diagnostic': typeof AuthenticatedAppsRightSideDiagnosticRoute
  '/_authenticated/apps/seeds-pipeline': typeof AuthenticatedAppsSeedsPipelineRoute
  '/_authenticated/dashboard/foundation-kit': typeof AuthenticatedDashboardFoundationKitRoute
  '/_authenticated/dashboard/inner-circle': typeof AuthenticatedDashboardInnerCircleRoute
  '/_authenticated/learn/$slug': typeof AuthenticatedLearnSlugRouteWithChildren
  '/api/cron/sync-fx': typeof ApiCronSyncFxRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/products/garden/$garden': typeof ProductsGardenGardenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/admin/curriculum/$productSlug': typeof AuthenticatedAdminCurriculumProductSlugRoute
  '/_authenticated/dashboard/products/free': typeof AuthenticatedDashboardProductsFreeRoute
  '/_authenticated/dashboard/products/paid': typeof AuthenticatedDashboardProductsPaidRoute
  '/_authenticated/learn/$slug/$lessonSlug': typeof AuthenticatedLearnSlugLessonSlugRoute
  '/api/email/auth/preview': typeof ApiEmailAuthPreviewRoute
  '/api/email/auth/webhook': typeof ApiEmailAuthWebhookRoute
  '/api/email/queue/process': typeof ApiEmailQueueProcessRoute
  '/_authenticated/learn/$slug/': typeof AuthenticatedLearnSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/align-accelerate-excel'
    | '/apply'
    | '/contact'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/privacy'
    | '/rate-card'
    | '/refund-policy'
    | '/reset-password'
    | '/sars-calculator'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/checkout/success'
    | '/products/$slug'
    | '/products/'
    | '/admin/contacts'
    | '/admin/import-contacts'
    | '/admin/incidents'
    | '/admin/ledger'
    | '/admin/products'
    | '/apps/4e-content-calendar'
    | '/apps/consistency-blueprint'
    | '/apps/dares-asset-model'
    | '/apps/first-income-planner'
    | '/apps/knowledge-audit'
    | '/apps/ms-ts-ss'
    | '/apps/niche-clarity-builder'
    | '/apps/paids-auditor'
    | '/apps/right-side-diagnostic'
    | '/apps/seeds-pipeline'
    | '/dashboard/foundation-kit'
    | '/dashboard/inner-circle'
    | '/learn/$slug'
    | '/api/cron/sync-fx'
    | '/api/public/paystack-webhook'
    | '/api/public/stripe-webhook'
    | '/products/garden/$garden'
    | '/admin/'
    | '/dashboard/'
    | '/learn/'
    | '/admin/curriculum/$productSlug'
    | '/dashboard/products/free'
    | '/dashboard/products/paid'
    | '/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/learn/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/align-accelerate-excel'
    | '/apply'
    | '/contact'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/privacy'
    | '/rate-card'
    | '/refund-policy'
    | '/reset-password'
    | '/sars-calculator'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/account'
    | '/checkout/success'
    | '/products/$slug'
    | '/products'
    | '/admin/contacts'
    | '/admin/import-contacts'
    | '/admin/incidents'
    | '/admin/ledger'
    | '/admin/products'
    | '/apps/4e-content-calendar'
    | '/apps/consistency-blueprint'
    | '/apps/dares-asset-model'
    | '/apps/first-income-planner'
    | '/apps/knowledge-audit'
    | '/apps/ms-ts-ss'
    | '/apps/niche-clarity-builder'
    | '/apps/paids-auditor'
    | '/apps/right-side-diagnostic'
    | '/apps/seeds-pipeline'
    | '/dashboard/foundation-kit'
    | '/dashboard/inner-circle'
    | '/api/cron/sync-fx'
    | '/api/public/paystack-webhook'
    | '/api/public/stripe-webhook'
    | '/products/garden/$garden'
    | '/admin'
    | '/dashboard'
    | '/learn'
    | '/admin/curriculum/$productSlug'
    | '/dashboard/products/free'
    | '/dashboard/products/paid'
    | '/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/learn/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/align-accelerate-excel'
    | '/apply'
    | '/contact'
    | '/hook-generator'
    | '/login'
    | '/media-kit'
    | '/niche-clarity'
    | '/offer-builder'
    | '/privacy'
    | '/rate-card'
    | '/refund-policy'
    | '/reset-password'
    | '/sars-calculator'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/learn'
    | '/checkout/success'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/import-contacts'
    | '/_authenticated/admin/incidents'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/admin/products'
    | '/_authenticated/apps/4e-content-calendar'
    | '/_authenticated/apps/consistency-blueprint'
    | '/_authenticated/apps/dares-asset-model'
    | '/_authenticated/apps/first-income-planner'
    | '/_authenticated/apps/knowledge-audit'
    | '/_authenticated/apps/ms-ts-ss'
    | '/_authenticated/apps/niche-clarity-builder'
    | '/_authenticated/apps/paids-auditor'
    | '/_authenticated/apps/right-side-diagnostic'
    | '/_authenticated/apps/seeds-pipeline'
    | '/_authenticated/dashboard/foundation-kit'
    | '/_authenticated/dashboard/inner-circle'
    | '/_authenticated/learn/$slug'
    | '/api/cron/sync-fx'
    | '/api/public/paystack-webhook'
    | '/api/public/stripe-webhook'
    | '/products/garden/$garden'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/learn/'
    | '/_authenticated/admin/curriculum/$productSlug'
    | '/_authenticated/dashboard/products/free'
    | '/_authenticated/dashboard/products/paid'
    | '/_authenticated/learn/$slug/$lessonSlug'
    | '/api/email/auth/preview'
    | '/api/email/auth/webhook'
    | '/api/email/queue/process'
    | '/_authenticated/learn/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlignAccelerateExcelRoute: typeof AlignAccelerateExcelRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  HookGeneratorRoute: typeof HookGeneratorRoute
  LoginRoute: typeof LoginRoute
  MediaKitRoute: typeof MediaKitRoute
  NicheClarityRoute: typeof NicheClarityRoute
  OfferBuilderRoute: typeof OfferBuilderRoute
  PrivacyRoute: typeof PrivacyRoute
  RateCardRoute: typeof RateCardRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SarsCalculatorRoute: typeof SarsCalculatorRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiCronSyncFxRoute: typeof ApiCronSyncFxRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ProductsGardenGardenRoute: typeof ProductsGardenGardenRoute
  ApiEmailAuthPreviewRoute: typeof ApiEmailAuthPreviewRoute
  ApiEmailAuthWebhookRoute: typeof ApiEmailAuthWebhookRoute
  ApiEmailQueueProcessRoute: typeof ApiEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sars-calculator': {
      id: '/sars-calculator'
      path: '/sars-calculator'
      fullPath: '/sars-calculator'
      preLoaderRoute: typeof SarsCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-card': {
      id: '/rate-card'
      path: '/rate-card'
      fullPath: '/rate-card'
      preLoaderRoute: typeof RateCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-builder': {
      id: '/offer-builder'
      path: '/offer-builder'
      fullPath: '/offer-builder'
      preLoaderRoute: typeof OfferBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niche-clarity': {
      id: '/niche-clarity'
      path: '/niche-clarity'
      fullPath: '/niche-clarity'
      preLoaderRoute: typeof NicheClarityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hook-generator': {
      id: '/hook-generator'
      path: '/hook-generator'
      fullPath: '/hook-generator'
      preLoaderRoute: typeof HookGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align-accelerate-excel': {
      id: '/align-accelerate-excel'
      path: '/align-accelerate-excel'
      fullPath: '/align-accelerate-excel'
      preLoaderRoute: typeof AlignAccelerateExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/products/garden/$garden': {
      id: '/products/garden/$garden'
      path: '/products/garden/$garden'
      fullPath: '/products/garden/$garden'
      preLoaderRoute: typeof ProductsGardenGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-fx': {
      id: '/api/cron/sync-fx'
      path: '/api/cron/sync-fx'
      fullPath: '/api/cron/sync-fx'
      preLoaderRoute: typeof ApiCronSyncFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$slug': {
      id: '/_authenticated/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof AuthenticatedLearnSlugRouteImport
      parentRoute: typeof AuthenticatedLearnRoute
    }
    '/_authenticated/dashboard/inner-circle': {
      id: '/_authenticated/dashboard/inner-circle'
      path: '/inner-circle'
      fullPath: '/dashboard/inner-circle'
      preLoaderRoute: typeof AuthenticatedDashboardInnerCircleRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/foundation-kit': {
      id: '/_authenticated/dashboard/foundation-kit'
      path: '/foundation-kit'
      fullPath: '/dashboard/foundation-kit'
      preLoaderRoute: typeof AuthenticatedDashboardFoundationKitRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/apps/seeds-pipeline': {
      id: '/_authenticated/apps/seeds-pipeline'
      path: '/apps/seeds-pipeline'
      fullPath: '/apps/seeds-pipeline'
      preLoaderRoute: typeof AuthenticatedAppsSeedsPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/right-side-diagnostic': {
      id: '/_authenticated/apps/right-side-diagnostic'
      path: '/apps/right-side-diagnostic'
      fullPath: '/apps/right-side-diagnostic'
      preLoaderRoute: typeof AuthenticatedAppsRightSideDiagnosticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/paids-auditor': {
      id: '/_authenticated/apps/paids-auditor'
      path: '/apps/paids-auditor'
      fullPath: '/apps/paids-auditor'
      preLoaderRoute: typeof AuthenticatedAppsPaidsAuditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/niche-clarity-builder': {
      id: '/_authenticated/apps/niche-clarity-builder'
      path: '/apps/niche-clarity-builder'
      fullPath: '/apps/niche-clarity-builder'
      preLoaderRoute: typeof AuthenticatedAppsNicheClarityBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/ms-ts-ss': {
      id: '/_authenticated/apps/ms-ts-ss'
      path: '/apps/ms-ts-ss'
      fullPath: '/apps/ms-ts-ss'
      preLoaderRoute: typeof AuthenticatedAppsMsTsSsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/knowledge-audit': {
      id: '/_authenticated/apps/knowledge-audit'
      path: '/apps/knowledge-audit'
      fullPath: '/apps/knowledge-audit'
      preLoaderRoute: typeof AuthenticatedAppsKnowledgeAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/first-income-planner': {
      id: '/_authenticated/apps/first-income-planner'
      path: '/apps/first-income-planner'
      fullPath: '/apps/first-income-planner'
      preLoaderRoute: typeof AuthenticatedAppsFirstIncomePlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/dares-asset-model': {
      id: '/_authenticated/apps/dares-asset-model'
      path: '/apps/dares-asset-model'
      fullPath: '/apps/dares-asset-model'
      preLoaderRoute: typeof AuthenticatedAppsDaresAssetModelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/consistency-blueprint': {
      id: '/_authenticated/apps/consistency-blueprint'
      path: '/apps/consistency-blueprint'
      fullPath: '/apps/consistency-blueprint'
      preLoaderRoute: typeof AuthenticatedAppsConsistencyBlueprintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/4e-content-calendar': {
      id: '/_authenticated/apps/4e-content-calendar'
      path: '/apps/4e-content-calendar'
      fullPath: '/apps/4e-content-calendar'
      preLoaderRoute: typeof AuthenticatedApps4eContentCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incidents': {
      id: '/_authenticated/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import-contacts': {
      id: '/_authenticated/admin/import-contacts'
      path: '/import-contacts'
      fullPath: '/admin/import-contacts'
      preLoaderRoute: typeof AuthenticatedAdminImportContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/learn/$slug/': {
      id: '/_authenticated/learn/$slug/'
      path: '/'
      fullPath: '/learn/$slug/'
      preLoaderRoute: typeof AuthenticatedLearnSlugIndexRouteImport
      parentRoute: typeof AuthenticatedLearnSlugRoute
    }
    '/api/email/queue/process': {
      id: '/api/email/queue/process'
      path: '/api/email/queue/process'
      fullPath: '/api/email/queue/process'
      preLoaderRoute: typeof ApiEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/webhook': {
      id: '/api/email/auth/webhook'
      path: '/api/email/auth/webhook'
      fullPath: '/api/email/auth/webhook'
      preLoaderRoute: typeof ApiEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/auth/preview': {
      id: '/api/email/auth/preview'
      path: '/api/email/auth/preview'
      fullPath: '/api/email/auth/preview'
      preLoaderRoute: typeof ApiEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$slug/$lessonSlug': {
      id: '/_authenticated/learn/$slug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/$slug/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedLearnSlugLessonSlugRouteImport
      parentRoute: typeof AuthenticatedLearnSlugRoute
    }
    '/_authenticated/dashboard/products/paid': {
      id: '/_authenticated/dashboard/products/paid'
      path: '/products/paid'
      fullPath: '/dashboard/products/paid'
      preLoaderRoute: typeof AuthenticatedDashboardProductsPaidRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/products/free': {
      id: '/_authenticated/dashboard/products/free'
      path: '/products/free'
      fullPath: '/dashboard/products/free'
      preLoaderRoute: typeof AuthenticatedDashboardProductsFreeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/curriculum/$productSlug': {
      id: '/_authenticated/admin/curriculum/$productSlug'
      path: '/curriculum/$productSlug'
      fullPath: '/admin/curriculum/$productSlug'
      preLoaderRoute: typeof AuthenticatedAdminCurriculumProductSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminImportContactsRoute: typeof AuthenticatedAdminImportContactsRoute
  AuthenticatedAdminIncidentsRoute: typeof AuthenticatedAdminIncidentsRoute
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCurriculumProductSlugRoute: typeof AuthenticatedAdminCurriculumProductSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminImportContactsRoute: AuthenticatedAdminImportContactsRoute,
  AuthenticatedAdminIncidentsRoute: AuthenticatedAdminIncidentsRoute,
  AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCurriculumProductSlugRoute:
    AuthenticatedAdminCurriculumProductSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardFoundationKitRoute: typeof AuthenticatedDashboardFoundationKitRoute
  AuthenticatedDashboardInnerCircleRoute: typeof AuthenticatedDashboardInnerCircleRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardProductsFreeRoute: typeof AuthenticatedDashboardProductsFreeRoute
  AuthenticatedDashboardProductsPaidRoute: typeof AuthenticatedDashboardProductsPaidRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardFoundationKitRoute:
      AuthenticatedDashboardFoundationKitRoute,
    AuthenticatedDashboardInnerCircleRoute:
      AuthenticatedDashboardInnerCircleRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardProductsFreeRoute:
      AuthenticatedDashboardProductsFreeRoute,
    AuthenticatedDashboardProductsPaidRoute:
      AuthenticatedDashboardProductsPaidRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedLearnSlugRouteChildren {
  AuthenticatedLearnSlugLessonSlugRoute: typeof AuthenticatedLearnSlugLessonSlugRoute
  AuthenticatedLearnSlugIndexRoute: typeof AuthenticatedLearnSlugIndexRoute
}

const AuthenticatedLearnSlugRouteChildren: AuthenticatedLearnSlugRouteChildren =
  {
    AuthenticatedLearnSlugLessonSlugRoute:
      AuthenticatedLearnSlugLessonSlugRoute,
    AuthenticatedLearnSlugIndexRoute: AuthenticatedLearnSlugIndexRoute,
  }

const AuthenticatedLearnSlugRouteWithChildren =
  AuthenticatedLearnSlugRoute._addFileChildren(
    AuthenticatedLearnSlugRouteChildren,
  )

interface AuthenticatedLearnRouteChildren {
  AuthenticatedLearnSlugRoute: typeof AuthenticatedLearnSlugRouteWithChildren
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
}

const AuthenticatedLearnRouteChildren: AuthenticatedLearnRouteChildren = {
  AuthenticatedLearnSlugRoute: AuthenticatedLearnSlugRouteWithChildren,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
}

const AuthenticatedLearnRouteWithChildren =
  AuthenticatedLearnRoute._addFileChildren(AuthenticatedLearnRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRouteWithChildren
  AuthenticatedApps4eContentCalendarRoute: typeof AuthenticatedApps4eContentCalendarRoute
  AuthenticatedAppsConsistencyBlueprintRoute: typeof AuthenticatedAppsConsistencyBlueprintRoute
  AuthenticatedAppsDaresAssetModelRoute: typeof AuthenticatedAppsDaresAssetModelRoute
  AuthenticatedAppsFirstIncomePlannerRoute: typeof AuthenticatedAppsFirstIncomePlannerRoute
  AuthenticatedAppsKnowledgeAuditRoute: typeof AuthenticatedAppsKnowledgeAuditRoute
  AuthenticatedAppsMsTsSsRoute: typeof AuthenticatedAppsMsTsSsRoute
  AuthenticatedAppsNicheClarityBuilderRoute: typeof AuthenticatedAppsNicheClarityBuilderRoute
  AuthenticatedAppsPaidsAuditorRoute: typeof AuthenticatedAppsPaidsAuditorRoute
  AuthenticatedAppsRightSideDiagnosticRoute: typeof AuthenticatedAppsRightSideDiagnosticRoute
  AuthenticatedAppsSeedsPipelineRoute: typeof AuthenticatedAppsSeedsPipelineRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedLearnRoute: AuthenticatedLearnRouteWithChildren,
  AuthenticatedApps4eContentCalendarRoute:
    AuthenticatedApps4eContentCalendarRoute,
  AuthenticatedAppsConsistencyBlueprintRoute:
    AuthenticatedAppsConsistencyBlueprintRoute,
  AuthenticatedAppsDaresAssetModelRoute: AuthenticatedAppsDaresAssetModelRoute,
  AuthenticatedAppsFirstIncomePlannerRoute:
    AuthenticatedAppsFirstIncomePlannerRoute,
  AuthenticatedAppsKnowledgeAuditRoute: AuthenticatedAppsKnowledgeAuditRoute,
  AuthenticatedAppsMsTsSsRoute: AuthenticatedAppsMsTsSsRoute,
  AuthenticatedAppsNicheClarityBuilderRoute:
    AuthenticatedAppsNicheClarityBuilderRoute,
  AuthenticatedAppsPaidsAuditorRoute: AuthenticatedAppsPaidsAuditorRoute,
  AuthenticatedAppsRightSideDiagnosticRoute:
    AuthenticatedAppsRightSideDiagnosticRoute,
  AuthenticatedAppsSeedsPipelineRoute: AuthenticatedAppsSeedsPipelineRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AlignAccelerateExcelRoute: AlignAccelerateExcelRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  HookGeneratorRoute: HookGeneratorRoute,
  LoginRoute: LoginRoute,
  MediaKitRoute: MediaKitRoute,
  NicheClarityRoute: NicheClarityRoute,
  OfferBuilderRoute: OfferBuilderRoute,
  PrivacyRoute: PrivacyRoute,
  RateCardRoute: RateCardRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SarsCalculatorRoute: SarsCalculatorRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiCronSyncFxRoute: ApiCronSyncFxRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ProductsGardenGardenRoute: ProductsGardenGardenRoute,
  ApiEmailAuthPreviewRoute: ApiEmailAuthPreviewRoute,
  ApiEmailAuthWebhookRoute: ApiEmailAuthWebhookRoute,
  ApiEmailQueueProcessRoute: ApiEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
